### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xzyLearn2rock**
Making it easier for people to understand what this project is about.

### CODE REVIEW

**Comment by xzyLearn2rock** [comment]
hi,can you get this massage?@sxxlearn2rock

**Comment by xzyLearn2rock** [comment]
原来这个是可以支持中文的，
`#include<iostream>
using namespace std;
int main(){
     cout << "hello GitHub" << endl;
     return 0;
}`

**Comment by xzyLearn2rock** [comment]
自己给自己评论，请问你是尔康么？:+ 1:

**Comment by sxxlearn2rock** [comment]
Yes,I recived your message.You are too fat.

2016-05-27



sxx_uestc



发件人：xzyLearn2rock <notifications@github.com>
发送时间：2016-05-27 09:58
主题：Re: [xzyLearn2rock/Hello-GitHub] Update README.md (#8)
收件人："xzyLearn2rock/Hello-GitHub"<Hello-GitHub@noreply.github.com>
抄送："sxxlearn2rock"<sxx_uestc@163.com>,"Mention"<mention@noreply.github.com>

hi,can you get this massage?@sxxlearn2rock

**Comment by xzyLearn2rock** [comment]
测试一下表情功能`:+ 1:`

**Comment by sxxlearn2rock** [comment]
哎哟，不错哦，都开始构建团队了。我都没弄过这个，你学会了要教我啊。

2016-05-27



sxx_uestc



发件人：xzyLearn2rock <notifications@github.com>
发送时间：2016-05-27 09:58
主题：Re: [xzyLearn2rock/Hello-GitHub] Update README.md (#8)
收件人："xzyLearn2rock/Hello-GitHub"<Hello-GitHub@noreply.github.com>
抄送："sxxlearn2rock"<sxx_uestc@163.com>,"Mention"<mention@noreply.github.com>

hi,can you get this massage?@sxxlearn2rock

**Pull request merged**
